# Generated by Django 5.1 on 2025-11-05 02:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Room",
            fields=[
                (
                    "room_id",
                    models.CharField(
                        editable=False, max_length=8, primary_key=True, serialize=False
                    ),
                ),
                (
                    "room_code",
                    models.CharField(editable=False, max_length=6, unique=True),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("waiting", "대기 중"),
                            ("playing", "플레이 중"),
                            ("finished", "완료"),
                        ],
                        default="waiting",
                        max_length=20,
                    ),
                ),
                ("max_players", models.IntegerField(default=4)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "mode",
                    models.CharField(
                        choices=[
                            ("steady_beat", "Steady Beat"),
                            ("pulse_rush", "Pulse Rush"),
                        ],
                        max_length=20,
                    ),
                ),
                ("time_limit_seconds", models.IntegerField(default=120)),
                ("bpm_min", models.IntegerField(blank=True, null=True)),
                ("bpm_max", models.IntegerField(blank=True, null=True)),
                ("started_at", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Player",
            fields=[
                (
                    "player_id",
                    models.CharField(
                        editable=False, max_length=36, primary_key=True, serialize=False
                    ),
                ),
                ("nickname", models.CharField(max_length=10)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("waiting", "대기 중"),
                            ("playing", "플레이 중"),
                            ("finished", "완료"),
                        ],
                        default="waiting",
                        max_length=20,
                    ),
                ),
                ("is_host", models.BooleanField(default=False)),
                ("joined_at", models.DateTimeField(auto_now_add=True)),
                (
                    "room",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="players",
                        to="rooms.room",
                    ),
                ),
            ],
            options={
                "ordering": ["joined_at"],
            },
        ),
    ]
